services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: quarta-capa
      POSTGRES_PASSWORD: quartacapa
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    restart: unless-stopped