package com.quartacapa.livro.model;

public enum AnoEscolarEnum {

    NAO_SE_APLICA,
    PRIMEIRO_ANO_FUNDAMENTAL,
    SEGUNDO_ANO_FUNDAMENTAL,
    TERCEIRO_ANO_FUNDAMENTAL,
    QUARTO_ANO_FUNDAMENTAL,
    QUINTO_ANO_FUNDAMENTAL,
    SEXTO_ANO_FUNDAMENTAL,
    SETIMO_ANO_FUNDAMENTAL,
    OITAVO_ANO_FUNDAMENTAL,
    NONO_ANO_FUNDAMMENTAL,
    PRIMEIRO_ANO_MEDIO,
    SEGUNDO_ANO_MEDIO,
    TERCEIRO_ANO_MEDIO
}
